name: CI Pipeline

on:
  push:

jobs:
  run-pipeline:
    name: Run CI Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Install dependencies
        run: |
          sudo apt update \
          && sudo apt install --no-install-recommends -y cmake ninja-build lcov gcc g++ make libc6-dev
          wget -q https://github.com/xpack-dev-tools/arm-none-eabi-gcc-xpack/releases/download/v13.3.1-1.1/xpack-arm-none-eabi-gcc-13.3.1-1.1-linux-x64.tar.gz
          tar -xzf xpack-arm-none-eabi-gcc-13.3.1-1.1-linux-x64.tar.gz
          echo "xpack-arm-none-eabi-gcc-13.3.1-1.1/bin/" >> $GITHUB_PATH
          
      - name: Build firmware binary
        # Release build doesnt exist yet so use Debug for now
        run: ./scripts/run.sh build Debug

      - name: Build and run unit tests
        run: ./scripts/run.sh test

      - name: Run formatting check
        uses: waterloo-rocketry/actions/clang-format-check@main
        with:
            clang-format-config-path: 'src/third_party/rocketlib/.clang-format'
            c-source-files: 'src/application/*/*.c src/application/*/*.h src/drivers/*/*.c src/drivers/*/*.h src/common/*/*.h'
