name: C Coding Style Check

# Runs on pushes to pull request
on: pull_request

jobs:
  # Build job
  clang-format-style-check:
    name: C Coding Style Check (clang-format check)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Run formatting check
        uses: waterloo-rocketry/actions/clang-format-check@main
        with:
          clang-format-config-path: 'src/third_party/rocketlib/.clang-format'
          c-source-files: 'src/application/*/*.c src/application/*/*.h src/drivers/*/*.c src/drivers/*/*.h'
